name: portfolio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  auto_size_text: ^3.0.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2
  expandable: ^5.0.1
  url_launcher: ^6.2.5
  flutter_markdown: ^0.7.3
  markdown: ^7.2.2
  skeletonizer: ^1.4.1+1

dev_dependencies: 
  flutter_lints: ^3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/logos/
    - assets/images/skills/
    - assets/images/projects/
    - assets/icons/

  fonts:
    - family: Mova
      fonts:
        - asset: assets/fonts/Mova.otf
    - family: Beckman
      fonts:
        - asset: assets/fonts/Beckman.otf