name: portfolio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  auto_size_text: ^3.0.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Mova
      fonts:
        - asset: assets/fonts/Mova.otf
    - family: Beckman
      fonts:
        - asset: assets/fonts/Beckman.otf